### ISSUE TITLE
Missing dependecy

### ISSUE THREAD

**Issue by teoc98** [asoderman/docCLI#7]
```
Traceback (most recent call last):
  File "/home/matteo/.local/bin/sheets", line 5, in <module>
    from docCLI.sheets import open_sheets
  File "/home/matteo/.local/share/pipx/venvs/doccli/lib/python3.12/site-packages/docCLI/sheets.py", line 5, in <module>
    from docCLI.core import create_url_creator, get_file_id, download_file
  File "/home/matteo/.local/share/pipx/venvs/doccli/lib/python3.12/site-packages/docCLI/core.py", line 8, in <module>
    from docCLI.google import drive_service
  File "/home/matteo/.local/share/pipx/venvs/doccli/lib/python3.12/site-packages/docCLI/google.py", line 6, in <module>
    from oauth2client import client
ModuleNotFoundError: No module named 'oauth2client'
```
Solved with
```
cd <venv dir>
bin/python -m pip install oauth2client
```

**Comment by poehlert** [comment]
If you're using pipx
```
pipx inject doccli oauth2client;
```
